# Generated by Django 4.0.4 on 2022-05-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('otp', models.IntegerField(max_length=4)),
            ],
        ),
    ]
