# Generated by Django 4.0.4 on 2022-05-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='otp',
            field=models.IntegerField(default=0),
        ),
    ]
