# Generated by Django 4.0.4 on 2022-05-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='lab',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
