# Generated by Django 4.0.4 on 2022-05-12 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_sample_lab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='patient',
        ),
        migrations.AddField(
            model_name='sample',
            name='phone',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='phone', to='backend.patient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sample',
            name='lab',
            field=models.CharField(default='NONE', max_length=10),
        ),
        migrations.AlterField(
            model_name='sample',
            name='status',
            field=models.CharField(default='NONE', max_length=10),
        ),
    ]
