# Generated by Django 4.0.4 on 2022-05-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_sample_patient_sample_phone_alter_sample_lab_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
