# Generated by Django 4.0.4 on 2022-05-12 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_sample_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
